image: node:9.11.1

pages:
  script:
  - mkdir -p ./public/
  - cd website
  - yarn install
  - yarn build
  - mv ./website/build ../../public

  artifacts:
    paths:
    - public
  
  only:
  - master
