image: node:9.11.1

pages:
  script:
  - mkdir -p ./public/
  - cd website
  - yarn install
  - yarn build
  - mv ./build/test-site ../public

  artifacts:
    paths:
    - public
  
  only:
  - master
